### ISSUE TITLE
検証環境を整える必要あり(ネットワーク)

### ISSUE THREAD

**Issue by y-ogawara** [y-ogawara/01-Spica-Android#164]
ネットワークの問題っぽいけどソフトウェアなのでここで

パケットが消えていることがあるので、その理由を突き止めて、安定的に動く環境を構築する

**Comment by multiverse2011** [comment]
いまいちパケットがどういう風に流れてるのか全容がつかめないので可視化する必要あり．
デバッグ環境の整え方が直近の課題．

**Comment by multiverse2011** [comment]
## TODO
- APを3台から1台に
現状だと3台だがメーカーのスペック値（しかもメーカーで検証済み）によると40クライアントまでは安定的に接続できる．127台まで動作はできるっぽい

- APのチャネルを確認
前回手動設定でチャネルを固定していたが実際には帯域幅が40MHzなどで設定されているため隣り合うチャネルで設定すると干渉していた可能性あり．ただAndroidのWiFI Analyzer的なやつで見たときは鑑賞しているふうには見えなかった．

- APの名前を変える
前回はAP名をすべて同じにしていた．挙動として起こり得るのが電界強度がほぼ同じ同一名称のAPが飛んでいるとローミングを何度も繰り返してしまうというもの．そもそもESPのWiFiがそこまで賢いとは思えずローミング処理的なものは実装されていない匂いすら感じる．

- パケットキャプチャして目視で死んでいるパケットを確認する．
@multiverse2011 亭にパケットミラーリングができるL2スイッチがあるのでそれでAPを通過したパケットを拾って確認する．

**Comment by multiverse2011** [comment]
## 参考
- メーカサイト（これのAT-MWS1750AP）
https://www.allied-telesis.co.jp/products/list/wireless/mws_ap/catalog.html

**Comment by y-ogawara** [comment]
APの電波強度チェック結果

適当においた状態で3号館2Fをすべてカバーすることができた、指向性はそこまで無さそう
