### ISSUE TITLE
speed値の設定方法の変更

### ISSUE THREAD

**Issue by y-ogawara** [y-ogawara/01-Spica-Android#167]
### 概要
- 現状は1,2,3を送っている
これは100とか150とかにするべきでは、esp側で速度を持つべきじゃない

### 想定される解決策
- esp側は以前の速度実装に戻し、アプリ(クライアント)側で対応する

### リンクとか
-

ESP側にも登録したい

**Comment by Dai1678** [comment]
fix/speedValue で作業中
デバッグ中

**Comment by Dai1678** [comment]
#174 で対応した
