### ISSUE TITLE
defaultで設定されるport番号の変更

### ISSUE THREAD

**Issue by y-ogawara** [y-ogawara/01-Spica-Android#168]
### 概要
- 10000ポートは使うべきではなかったっぽい

### 想定される解決策
- 50000ポートを使う

**Comment by multiverse2011** [comment]
## メモ
TCP，UDPにおけるポート番号はある程度の範囲はアプリケーションによって決まっている．

### 0-1023
いわゆるWell-knownポート．HTTPの80番とかSSHの22番

### 1024-49151
Registerdポート．IANAにより登録済み．プロクシの8080番とか

### 49152–65535
自由に使えるやつ．Spicaだとudpの送信時の送信元ポートをこの範囲でランダムに選んでいることがわかる（Andoridの実装）

https://ja.wikipedia.org/wiki/TCP%E3%82%84UDP%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%9D%E3%83%BC%E3%83%88%E7%95%AA%E5%8F%B7%E3%81%AE%E4%B8%80%E8%A6%A7

**Comment by multiverse2011** [comment]
@Dai1678 これ早めにfixしといてくれ

**Comment by Dai1678** [comment]
#175 で完了
