### ISSUE TITLE
Kioskモードの実装

### ISSUE THREAD

**Issue by Dai1678** [y-ogawara/01-Spica-Android#181]
### 概要
- イベント中で参加者にアプリを閉じられることが多々あるので、POSモードを導入してアプリから離れられないようにする

### 想定される解決策
- 

### リンクとか
-

**Comment by multiverse2011** [comment]
これPOSじゃなくてkioskだわ

**Comment by multiverse2011** [comment]
## 実現方法
https://lab.sonicmoov.com/development/app-dev/android-kiosk/

2通りのアプローチあり．

### ホーム画面アプリを作成
設定とSpicaしか立ちあげられないアプリをつくる．
### アプリ自体でロック機能を持つ
DeviceOwnerを使えばいけるらしいが初期化が必要だったりkindleではできなそう．

**Comment by multiverse2011** [comment]
https://github.com/FiriusFoxx/JustOneApp
なんかそれっぽいのあるわ

**Comment by multiverse2011** [comment]
https://github.com/t-robop/01-Spica-Launcher
らんちゃーつくった

**Comment by multiverse2011** [comment]
これ作ってから気がついたんやがSpica本体をHomeAppとして設定すれば良かったのでは :thinking:

**Comment by multiverse2011** [comment]
https://github.com/t-robop/01-Spica-Launcher で実装しました
