### ISSUE TITLE
詳細画面内のラジオボタン位置修正

### ISSUE THREAD

**Issue by Dai1678** [y-ogawara/01-Spica-Android#182]
### 概要
- 速度段階設定のラジオボタン位置の修正が必要.誤タップが多い
それぞれのラジオボタンのマージンが小さすぎる

- 回転ブロックの左・右のラジオボタンも同様

- 回転ブロックに関しては、ラジオボタンそれぞれの位置が近すぎる

- その他のUI部品とのマージンも近すぎるので調整が必要

### 想定される解決策
- 該当のlayoutファイルの修正

### リンクとか
-

**Comment by TaigaNatto** [comment]
ラジオボタンが最適なのか考える必要がある

**Comment by Dai1678** [comment]
リリースまで時間無いので、パッと思いつかなかったら概要の修正を優先した方が良いと思われる

**Comment by TaigaNatto** [comment]
せやな(それくらいの修正なら @Dai1678 がやってもいいのでは・・・？ )

**Comment by Dai1678** [comment]
案が出なければ俺対応にしても構わないので、その辺の決定権は任せます
