### ISSUE TITLE
ブロック編集画面内のほぞんボタン・すてるボタン位置修正

### ISSUE THREAD

**Issue by Dai1678** [y-ogawara/01-Spica-Android#183]
### 概要
- 編集画面で「ほぞん」ボタンと「すてる」ボタンの位置が縦並びになっていることで、誤タップが多い印象. 縦並びだと指の置き方的に両方のボタンに重なる
AndroidのAlertDialogのデフォルトボタンのように、横並びのほうがUX的に最適では。

### 想定される解決策
- 「すてる」ボタンと「ほぞん」ボタンの位置調整、該当layoutファイルで修正

### リンクとか
-

**Comment by TaigaNatto** [comment]
横並びにしようとめっちゃ考えたけど、縦長にするかラジオボタンを消すかしか思いつかなかった

**Comment by Dai1678** [comment]
ボタン横並びにしても、ラジオボタンとの位置競合は起きないイメージなんだけど、そんなことはない？

**Comment by TaigaNatto** [comment]
え、テキストサイズそのままで横並びにしたらフラグメントサイズ変えないと収まらなくない？
@Dai1678 の脳内デザインを見せてほしい

**Comment by Dai1678** [comment]
実際試してないのでソースはない　ごめん
押し間違えの事例はあったので何らかの対応は必要だと思う
