### ISSUE TITLE
シークバーの挙動の最適化

### ISSUE THREAD

**Issue by Dai1678** [y-ogawara/01-Spica-Android#184]
### 概要
- シークバー上をタップした際の値変更とバーの挙動が正常に適用されていない場合がある

- シークバーとそれ以外の位置が近すぎる

### 想定される解決策
- シークバーのリスナー処理の見直し
- 該当layoutファイルでマージンの調整

### リンクとか
-

**Comment by TaigaNatto** [comment]
```
シークバー上をタップした際の値変更とバーの挙動が正常に適用されていない場合がある
```
再現手順を教えてください！

**Comment by TaigaNatto** [comment]
```
シークバーとそれ以外の位置が近すぎる
```
そもそもフラグメントが小さい？

**Comment by y-ogawara** [comment]
タッチイベントの範囲が狭いって感じ
反映されないのは @だいさく

**Comment by TaigaNatto** [comment]
範囲了解
そろそろ詰めきれなくなってる感ある

**Comment by y-ogawara** [comment]
実機で試すとわかりやすいんだけど、何回かタップしないと動かせないのがわりとストレスになる

**Comment by Dai1678** [comment]
@y-ogawara が話してる範囲の問題だけで大丈夫
それによって操作したつもりが反映されてないという認識

**Comment by TaigaNatto** [comment]
おっけー
